name = "doh"
type = "javascript"
main = "index.js"

#account_id = ""
workers_dev = true
compatibility_date = "2022-08-07"
route = "dns.hafidzradhival.my.id/dns-query"
#custom_domain = true
#zone_id = ""
